name: CI/CD Go + Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Installation de Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Lancer les tests Go
      run: go test ./...

    - name: Compiler le projet Go
      run: go build -v ./...

    # - name: Connexion à Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Construction de l'image Docker
    #   run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/forum-app:latest .

    # - name: Publication de l'image Docker
    #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/forum-app:latest